name: Bug Report
description: Report a reproducible bug in rn-sane-charts
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for filing a bug. Please provide a minimal, reproducible case.

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Briefly describe the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Provide numbered steps and, if possible, a minimal code sample.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include versions and platform details.
      placeholder: |
        - @rn-sane-charts/rn:
        - @shopify/react-native-skia:
        - react-native:
        - expo:
        - Platform/device:
    validations:
      required: true

  - type: checkboxes
    id: checks
    attributes:
      label: Confirmations
      options:
        - label: I searched existing issues and did not find a duplicate.
          required: true
        - label: I can reproduce this on current `main` (or latest release).
          required: true
