name: Feature Request
description: Propose a feature aligned with MVP direction
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Feature requests should describe the user problem first, not just implementation ideas.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user pain does this solve?
      placeholder: Describe the current limitation.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Keep this concise and implementation-agnostic where possible.
      placeholder: Describe what should exist.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Other options and why they are weaker.
    validations:
      required: false

  - type: checkboxes
    id: scope_checks
    attributes:
      label: Scope checks
      options:
        - label: I reviewed `docs/PRD.md` and believe this is in scope.
          required: true
        - label: I understand this may be redirected to Discussions before any PR is accepted.
          required: true
